# Generated by Django 6.0.5 on 2026-05-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_at_imaging', models.IntegerField()),
                ('loinc_code', models.CharField(max_length=100)),
                ('loinc_contrast', models.CharField(max_length=100)),
                ('loinc_modality', models.CharField(max_length=100)),
                ('modality', models.CharField(choices=[('PET', 'PET'), ('CT', 'CT'), ('SPECT', 'SPECT'), ('MRI', 'MRI')], max_length=100)),
                ('year_of_study', models.DateField()),
                ('scan_timepoint', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('submitter_id', models.CharField(max_length=500)),
                ('subject_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('residence_country', models.CharField(max_length=500)),
                ('race', models.CharField(max_length=500)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('OTHER', 'Other'), ('NR', 'Not Reported')], default='NR', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_size', models.DecimalField(decimal_places=4, max_digits=12)),
                ('md5sum', models.CharField(max_length=200)),
                ('modality', models.CharField(choices=[('PET', 'PET'), ('CT', 'CT'), ('SPECT', 'SPECT'), ('MRI', 'MRI')], max_length=50)),
                ('series_description', models.CharField(max_length=500)),
                ('manufacturer', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('software_version', models.CharField(max_length=200)),
                ('collimator', models.CharField(default='NA', max_length=200)),
                ('attenuation_correction', models.CharField(default='NA', max_length=200)),
                ('convolution_kernel', models.CharField(default='NA', max_length=200)),
                ('energy_window', models.CharField(default='NA', max_length=200)),
                ('imaging_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_files', to='db_app.imagingstudy')),
            ],
        ),
        migrations.CreateModel(
            name='AbsorbedDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('liver', 'Liver'), ('kidneys', 'Kidneys'), ('marrow', 'Marrow'), ('salivary_glands', 'Salivary Glands'), ('lungs', 'Lungs'), ('spleen', 'Spleen'), ('rest_of_body', 'Rest of Body'), ('lesion', 'Lesion')], max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('mean', models.DecimalField(decimal_places=4, max_digits=12)),
                ('stdev', models.DecimalField(decimal_places=4, max_digits=12)),
                ('d50', models.DecimalField(decimal_places=4, max_digits=12)),
                ('d90', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lesion_vol', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dosimetry_method', models.CharField(choices=[('MIRD', 'MIRD'), ('voxel_dosimetry', 'Voxel Dosimetry'), ('monte_carlo', 'Monte Carlo'), ('Other', 'Other')], max_length=100)),
                ('software_used', models.CharField(max_length=100)),
                ('time_activity_curve_fit', models.CharField(max_length=100)),
                ('imaging_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absorbed_dose_imaging', to='db_app.imagingstudy')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=500)),
                ('condition_code', models.CharField(max_length=100)),
                ('days_to_condition_start', models.IntegerField(blank=True, null=True)),
                ('days_to_condition_end', models.IntegerField(blank=True, null=True)),
                ('performance_ecog', models.CharField(blank=True, choices=[('0', 'ECOG 0'), ('1', 'ECOG 1'), ('2', 'ECOG 2'), ('3', 'ECOG 3'), ('4', 'ECOG 4'), ('5', 'ECOG 5')], max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='db_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_response', models.CharField(choices=[('complete_response', 'Complete Response'), ('partial_response', 'Partial Response'), ('stable_disease', 'Stable Disease'), ('progressive_disease', 'Progressive Disease'), ('not_evaluable', 'Not Evaluable')], max_length=100)),
                ('progression_free_survival', models.IntegerField()),
                ('overall_survival', models.IntegerField()),
                ('toxicity_grade', models.CharField(choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5')], max_length=100)),
                ('toxicity_organ', models.CharField(choices=[('liver', 'Liver'), ('kidneys', 'Kidneys'), ('marrow', 'Marrow'), ('salivary_glands', 'Salivary Glands'), ('lungs', 'Lungs'), ('spleen', 'Spleen'), ('rest_of_body', 'Rest of Body'), ('lesion', 'Lesion')], max_length=100)),
                ('days_to_progression', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_outcomes', to='db_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_surgery', models.DateTimeField()),
                ('primary_tumor_removal', models.BooleanField(default=False)),
                ('time_between_RPT_surgery', models.DecimalField(decimal_places=4, max_digits=12)),
                ('pre_tumor_volume', models.DecimalField(decimal_places=4, max_digits=12)),
                ('post_tumor_volume', models.DecimalField(decimal_places=4, max_digits=12)),
                ('debulking_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='db_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TherapyTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_type', models.CharField(choices=[('hormone_therapy', 'Hormone Therapy'), ('chemotherapy', 'Chemotherapy'), ('immunotherapy', 'Immunotherapy'), ('system_radiation_therapy', 'Systemic Radiation Therapy'), ('liver_directed_therapy', 'Liver Directed Therapy')], max_length=100)),
                ('start_therapy_date', models.DateTimeField()),
                ('end_therapy_date', models.DateTimeField()),
                ('time_between_rpt_other', models.DecimalField(decimal_places=4, max_digits=12)),
                ('pre_tumor_volume', models.DecimalField(decimal_places=4, max_digits=12)),
                ('post_tumor_volume', models.DecimalField(decimal_places=4, max_digits=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_treatments', to='db_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1)),
                ('radiopharmaceutical', models.CharField(max_length=500)),
                ('therapy_type', models.CharField(choices=[('A', 'Alpha'), ('B', 'Beta'), ('E', 'Auger Electron'), ('NR', 'Not Reported')], default='NR', max_length=10)),
                ('net_injected_activity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('therapeutic_target', models.CharField(max_length=500)),
                ('pre_sstr_pet', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('post_sstr_pet', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pre_chromogranin_a', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('post_chromogranin_a', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('overall_survival', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_cycles', to='db_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loinc_code', models.CharField(max_length=100)),
                ('lab_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lab_unit', models.CharField(max_length=100)),
                ('collection_time', models.DateTimeField(blank=True, null=True)),
                ('creatinine_clearance', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('treatment_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='db_app.treatmentcycle')),
            ],
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='treatment_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='db_app.treatmentcycle'),
        ),
        migrations.CreateModel(
            name='CaseID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_submitter_id', models.CharField(max_length=500)),
                ('treatment_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_ids', to='db_app.treatmentcycle')),
            ],
        ),
        migrations.CreateModel(
            name='TumorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tumor_site', models.CharField(max_length=500)),
                ('ajcc_stage', models.CharField(max_length=20)),
                ('tumor_grade', models.CharField(max_length=100)),
                ('liver_mets', models.BooleanField(default=False)),
                ('ki_67', models.DecimalField(decimal_places=4, max_digits=12)),
                ('pet_tumor_vol', models.DecimalField(decimal_places=4, max_digits=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_information', to='db_app.patient')),
            ],
        ),
    ]
