# Generated by Django 6.0.5 on 2026-05-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='treatment_cycle',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='imagingstudy',
            name='scan_timepoint',
        ),
        migrations.RemoveField(
            model_name='treatmentcycle',
            name='overall_survival',
        ),
        migrations.RemoveField(
            model_name='treatmentcycle',
            name='post_chromogranin_a',
        ),
        migrations.RemoveField(
            model_name='treatmentcycle',
            name='post_sstr_pet',
        ),
        migrations.RemoveField(
            model_name='treatmentcycle',
            name='pre_chromogranin_a',
        ),
        migrations.RemoveField(
            model_name='treatmentcycle',
            name='pre_sstr_pet',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='treatmentcycle',
            name='therapeutic_target',
            field=models.CharField(choices=[('liver', 'Liver'), ('kidneys', 'Kidneys'), ('marrow', 'Marrow'), ('salivary_glands', 'Salivary Glands'), ('lungs', 'Lungs'), ('spleen', 'Spleen'), ('rest_of_body', 'Rest of Body'), ('lesion', 'Lesion')], max_length=500),
        ),
        migrations.DeleteModel(
            name='CaseID',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
    ]
