# Generated by Django 6.0.5 on 2026-05-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_remove_labtest_treatment_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagingstudy',
            name='age_at_imaging',
        ),
        migrations.RemoveField(
            model_name='imagingstudy',
            name='loinc_code',
        ),
        migrations.RemoveField(
            model_name='imagingstudy',
            name='loinc_modality',
        ),
    ]
