# Generated by Django 6.0.5 on 2026-05-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_remove_imagingstudy_age_at_imaging_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absorbeddose',
            name='d50',
        ),
        migrations.RemoveField(
            model_name='absorbeddose',
            name='software_used',
        ),
        migrations.RemoveField(
            model_name='absorbeddose',
            name='stdev',
        ),
        migrations.RemoveField(
            model_name='absorbeddose',
            name='target_id',
        ),
    ]
