# Generated by Django 6.0.5 on 2026-05-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_remove_absorbeddose_d50_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaloutcome',
            name='toxicity_organ',
        ),
    ]
