# Generated by Django 6.0.5 on 2026-05-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_remove_clinicaloutcome_toxicity_organ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomfile',
            name='energy_window',
        ),
        migrations.RemoveField(
            model_name='dicomfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='dicomfile',
            name='md5sum',
        ),
        migrations.RemoveField(
            model_name='dicomfile',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='dicomfile',
            name='software_version',
        ),
    ]
