# Generated by Django 6.0.5 on 2026-05-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0006_remove_dicomfile_energy_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='file',
            field=models.FileField(default=None, upload_to='dicom/'),
        ),
    ]
