# Generated by Django 6.0.5 on 2026-05-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0007_dicomfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingstudy',
            name='year_of_study',
            field=models.IntegerField(),
        ),
    ]
